// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJnhFnOEHgbLRWrvj4lUi68W2Cjq4LiE',
    appId: '1:955251471854:web:21890a4f6e7c04f850caff',
    messagingSenderId: '955251471854',
    projectId: 'dothithongminhkl',
    authDomain: 'dothithongminhkl.firebaseapp.com',
    storageBucket: 'dothithongminhkl.appspot.com',
    measurementId: 'G-W0Y00PNN0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPMunfGp5LDs2ZCUPF9B_93sQFtF55OyM',
    appId: '1:955251471854:android:2f7a8d09be0d2ca250caff',
    messagingSenderId: '955251471854',
    projectId: 'dothithongminhkl',
    storageBucket: 'dothithongminhkl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYNHzHcMnrJ_won_KVTSmtepTnGKZ42BM',
    appId: '1:955251471854:ios:420bca4d1b07bb3c50caff',
    messagingSenderId: '955251471854',
    projectId: 'dothithongminhkl',
    storageBucket: 'dothithongminhkl.appspot.com',
    iosBundleId: 'n.quang.dothithongminhUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYNHzHcMnrJ_won_KVTSmtepTnGKZ42BM',
    appId: '1:955251471854:ios:c9946e5d484f34f550caff',
    messagingSenderId: '955251471854',
    projectId: 'dothithongminhkl',
    storageBucket: 'dothithongminhkl.appspot.com',
    iosBundleId: 'n.quang.dothithongminhUser.RunnerTests',
  );
}
